<a href="https://colab.research.google.com/github/sophioliveira/ICC_26/blob/main/Lista_05_Estruturas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introdução à Ciência da Computação (ICC)**
## **Lista 04: Laços**

Esse notebook contém lista de exercícios relacionados aos tópicos __laços, for, range, while, break, continue e laços aninhados__ em  __python__.


## **Professores**

<table>
<tr>
<td>
<center>
<img src="https://www.sorocaba.unesp.br/Home/Graduacao/EngenhariadeControleeAutomacao/alexandre/alex_marta1_small.jpg" height="100" style="float: left; margin-right: 5px;" border="10px" />
</center>
</td>

<td>
<center>
<img src="https://www.sorocaba.unesp.br/Home/Graduacao/EngenhariadeControleeAutomacao/leopoldo.gif" height="100" style="float: left; margin-right: 5px;" border="10px" />
</center>
</td>
</tr>
</table>

  __Prof. Dr. Alexandre da Silva Simões__ <br>
  __Prof. Dr. Leopoldo André Dutra Lusquinho Filho__ <br>
  Control and Automation Engineering Department (DECA) <br>
  Institute of Science and Technology<br>
  São Paulo State University (Unesp) <br>
  Campus Sorocaba <br>

---

## **Sumário**

- Vetores, matrizes e tensores
- Listas, conjuntos e tuplas
- Dicionários

Cada exercício possui:
1. Um campo de texto com **informações sobre a questão**
2. Uma célula para **escrever seu código**
3. Uma célula de **teste automático** do seu código
4. Outro campo de texto com algumas **reflexões**

**Obs**: Execute primeiro sua solução e depois execute a célula de teste.


---
## **Exercício 1: Manipulação de listas**

Em uma pequena cidade da região de Kanto, um jovem treinador está tentando entender melhor o desempenho de seu Pokémon em batalhas. Para isso, ele anotou alguns de seus atributos principais:

* HP (vida)
* Ataque
* Defesa
* Velocidade
* Ataque Especial

Esses valores são representados pela seguinte lista:



```
stats = [80, 100, 70, 90, 110]
```

O treinador ouviu falar que, para comparar diferentes Pokémon, é útil **normalizar** esses valores — ou seja, transformá-los para uma mesma escala, entre 0 e 1.

Para fazer isso, ele recebeu a seguinte orientação:

> Para cada valor da lista, subtraia o menor valor da lista e depois divida pelo intervalo total (máximo − mínimo).

Ou seja, para cada elemento x:

$normalizado = \frac{x - mínimo}{máximo - mínimo}$

---

## Tarefas

1. Converta a lista `stats` em um array NumPy.  
2. Sem usar funções prontas como `np.min`, `np.max` ou `np.mean`, determine:
   - o menor valor da lista  
   - o maior valor da lista  
3. Crie um novo array com os valores normalizados, seguindo a fórmula acima.  
4. Calcule manualmente a média dos valores normalizados:
   - some todos os valores  
   - divida pela quantidade de elementos  

---

## Restrições importantes

- Não use funções prontas como:
  - np.min, np.max, np.mean, np.std  
- Use apenas:
  - loops (`for`)  
  - operações básicas  
  - indexação  

---

## Dica

- Pense na normalização como “colocar todos os atributos na mesma régua”  
- O menor valor vira 0, o maior vira 1, e os outros ficam entre eles  



In [ ]:
# Escreva seu código aqui
import numpy as np

stats = [80, 100, 70, 90, 110]
v = np.array(stats) # Renamed from stats_array

min_val = v[0]
max_val = v[0]

for valor in v:
    if valor < min_val:
        min_val = valor
    elif valor > max_val:
        max_val = valor

v_norm = [] # Renamed from normalizados

for valor in v:
    normalizado = (valor - min_val) / (max_val - min_val)
    v_norm.append(normalizado)

soma = 0

for valor in v_norm:
    soma += valor

media = soma / len(v_norm)

print("Array original:", v)
print("Menor valor:", min_val)
print("Maior valor:", max_val)
print("Array normalizado:", v_norm)
print("Média dos valores normalizados:", media)

Array original: [ 80 100  70  90 110]
Menor valor: 70
Maior valor: 110
Array normalizado: [np.float64(0.25), np.float64(0.75), np.float64(0.0), np.float64(0.5), np.float64(1.0)]
Média dos valores normalizados: 0.5



### **Checagem**:

In [ ]:
# Não altere esse código! Apenas rode-o para checar seu resultado...
stats_ref = [80, 100, 70, 90, 110]
v_norm_ref = [0.25, 0.75, 0.0, 0.5, 1.0]
media_ref = 0.5

assert isinstance(v, np.ndarray), "v deve ser um numpy array"
assert list(v) == stats_ref, "v deve conter exatamente os valores de stats"
assert isinstance(v_norm, (list, np.ndarray)), "v_norm deve ser lista ou array"

for a, b in zip(v_norm, v_norm_ref):
    assert abs(a - b) < 1e-6, f"Erro na normalização: esperado {b}, obtido {a}"

assert abs(media - media_ref) < 1e-6, f"Média incorreta: esperado {media_ref}, obtido {media}"
print("Exercício correto!")

Exercício correto!


---
## **Exercício 2: Operações com Array e Indexação**

Considere a seguinte lista:

dados = [5, 10, 15, 20, 25, 30]

---

## Tarefas

1. Converta a lista `dados` em um array NumPy chamado `v`.

2. Usando **indexação**, obtenha:
   - o primeiro elemento  
   - o último elemento  

3. Usando **fatiamento (slicing)**, crie um novo array contendo apenas os elementos do índice 1 ao 4 (inclusive o 1 e exclusivo o 5).

4. Crie um novo array chamado `v_mod` onde:
   - os elementos de índice par (0, 2, 4, ...) são multiplicados por 2  
   - os elementos de índice ímpar permanecem iguais  

---

## Restrições

- Pode usar indexação e slicing (`[]`, `:`)
- Pode usar loops (`for`)
- Evite funções prontas que resolvam tudo diretamente

---

## Dica

- Lembre-se:
- índices começam em 0  
- slicing segue o padrão: início:fim  

In [ ]:
# Escreva seu código aqui...
import numpy as np

dados = [5, 10, 15, 20, 25, 30]

v = np.array(dados)

primeiro = v[0]
ultimo = v[-1]

sub = v[1:5]

v_mod = []

for i in range(len(v)):
  if(i % 2 == 0):
    v_mod.append(v[i] * 2)

  else:
    v_mod.append(v[i])

  v_mod_array = np.array(v_mod)

  print("Array original: ", v)
  print("Primeiro elemento: ", primeiro)
  print("Último elemento: ", ultimo)
  print("Slice: ", sub)
  print("Array modificado: ", v_mod_array)



Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10]
Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10 10]
Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10 10 30]
Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10 10 30 20]
Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10 10 30 20 50]
Array original:  [ 5 10 15 20 25 30]
Primeiro elemento:  5
Último elemento:  30
Slice:  [10 15 20 25]
Array modificado:  [10 10 30 20 50 30]


### **Checagem**:

In [ ]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

dados_ref = [5, 10, 15, 20, 25, 30]
primeiro_ref = 5
ultimo_ref = 30
slice_ref = [10, 15, 20, 25]
v_mod_ref = [10, 10, 30, 20, 50, 30]


assert isinstance(v, np.ndarray), "v deve ser um numpy array"
assert list(v) == dados_ref, "v deve conter os valores originais"
assert primeiro == primeiro_ref, "Primeiro elemento incorreto"
assert ultimo == ultimo_ref, "Último elemento incorreto"
assert list(sub) == slice_ref, "Slicing incorreto"
assert list(v_mod) == v_mod_ref, "v_mod incorreto"

print("Exercício correto!")

Exercício correto!


---
## **Exercício 3: Operações com Matrizes**

Considere a seguinte matriz de valores:

dados = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

---

## Tarefas

1. Converta a lista de listas `dados` em uma matriz NumPy chamada `M`.

2. Usando **indexação**, obtenha:
   - o elemento central da matriz  
   - o elemento do canto superior direito  

3. Usando **fatiamento (slicing)**, extraia:
   - a segunda linha da matriz  
   - a terceira coluna da matriz  

4. Crie uma nova matriz chamada `M_mod` onde:
   - todos os elementos da diagonal principal são multiplicados por 10  
   - os demais elementos permanecem iguais  

---

## Restrições

- Pode usar indexação (`M[i][j]` ou `M[i, j]`)
- Pode usar slicing (`:`)
- Pode usar loops (`for`)
- Evite funções prontas que façam tudo diretamente

---

## Dicas

- O elemento central está no meio da matriz  
- A diagonal principal contém elementos onde o índice da linha é igual ao da coluna  
- Para acessar colunas, pense em usar `:` nas linhas  

In [ ]:
# Entre com seu código aqui
import numpy as np

dados = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

M = np.array(dados)

centro = M[1,1]
sup_dir = M[0,2]
seg_l = M[1,:]
ter_l = M[:,2]

M_mod = np.copy(M)

for i in range(len(M)):
  for j in range(len(M[i])):
    if(i == j):
      M_mod[i,j] = M[i,j] * 10

print("Matriz original:\n ", M)
print("Elemento central: ", centro)
print("Elemento superior direito: ", sup_dir)
print("Segunda linha: ", seg_l)
print("Terceira coluna: ", ter_l)
print("Matriz modificada: \n", M_mod)


Matriz original:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento central:  5
Elemento superior direito:  3
Segunda linha:  [4 5 6]
Terceira coluna:  [3 6 9]
Matriz modificada: 
 [[10  2  3]
 [ 4 50  6]
 [ 7  8 90]]


### **Checagem**:

In [ ]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

dados_ref = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

centro_ref = 5
sup_dir_ref = 3
linha_ref = [4, 5, 6]
coluna_ref = [3, 6, 9]

M_mod_ref = [
    [10, 2, 3],
    [4, 50, 6],
    [7, 8, 90]
]

assert isinstance(M, np.ndarray), "M deve ser numpy array"
assert M.shape == (3, 3), "M deve ser 3x3"
assert M.tolist() == dados_ref, "M incorreta"

assert centro == centro_ref, "Elemento central incorreto"
assert sup_dir == sup_dir_ref, "Elemento superior direito incorreto"

assert list(linha2) == linha_ref, "Linha incorreta"
assert list(coluna3) == coluna_ref, "Coluna incorreta"

assert isinstance(M_mod, (list, np.ndarray)), "M_mod deve ser lista ou array"
assert np.array_equal(np.array(M_mod), np.array(M_mod_ref)), "M_mod incorreta"

print("Exercício correto!")

NameError: name 'linha2' is not defined

---

## **Exercício 4: Operações com tensores**

Considere a seguinte estrutura de dados, representando dois blocos de matrizes:

dados = [
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]

Essa estrutura pode ser interpretada como um tensor de dimensão (2 x 2 x 2).

---

## Tarefas

1. Converta `dados` em um tensor NumPy chamado `T`.

2. Usando **indexação**, obtenha:
   - o elemento na posição [0][1][1]  
   - o elemento na posição [1][0][0]  

3. Usando **fatiamento (slicing)**, extraia:
   - o primeiro “bloco” (primeira matriz 2x2)  
   - a segunda “camada” da última dimensão (ou seja, todos os elementos com índice final igual a 1)  

4. Crie um novo tensor chamado `T_mod` onde:
   - todos os elementos do primeiro bloco são multiplicados por 2  
   - os elementos do segundo bloco permanecem iguais  

---

## Restrições

- Pode usar indexação (`T[i][j][k]` ou `T[i, j, k]`)
- Pode usar slicing (`:`)
- Pode usar loops (`for`)
- Evite funções prontas que resolvam diretamente o problema

---

## Dicas

- Pense no tensor como uma “lista de matrizes”  
- O primeiro índice escolhe o bloco  
- O segundo índice escolhe a linha  
- O terceiro índice escolhe a coluna  

In [ ]:
# Escreva seu código aqui
import numpy as np

dados = [
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]

T = np.array(dados)
print(T)

elem1 = T[0, 1, 1]
elem2 = T[1, 0, 0]

bloco1 = T[0]
camada = T[:, :, 1]

T_mod = np.copy(T)
T_mod[0] = T_mod[0] * 2

print("Elemento na posição [0][1][1]:", elem1)
print("Elemento na posição [1][0][0]:", elem2)
print("Primeiro bloco (primeira matriz 2x2):\n", bloco1)
print("Segunda camada da última dimensão:\n", camada)
print("Tensor modificado:\n", T_mod)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Elemento na posição [0][1][1]: 4
Elemento na posição [1][0][0]: 5
Primeiro bloco (primeira matriz 2x2):
 [[1 2]
 [3 4]]
Segunda camada da última dimensão:
 [[2 4]
 [6 8]]
Tensor modificado:
 [[[2 4]
  [6 8]]

 [[5 6]
  [7 8]]]


### **Checagem**:

In [ ]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

dados_ref = [
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]

elem1_ref = 4   # T[0][1][1]
elem2_ref = 5   # T[1][0][0]

bloco_ref = [
    [1, 2],
    [3, 4]
]

camada_ref = [2, 4, 6, 8]

T_mod_ref = [
    [
        [2, 4],
        [6, 8]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]


assert isinstance(T, np.ndarray), "T deve ser numpy array"
assert T.shape == (2, 2, 2), "Shape incorreto"

assert elem1 == elem1_ref, "Elemento [0][1][1] incorreto"
assert elem2 == elem2_ref, "Elemento [1][0][0] incorreto"

assert np.array_equal(np.array(bloco1), np.array(bloco_ref)), "Bloco incorreto"

assert list(camada.flatten()) == camada_ref, "Camada incorreta"

assert np.array_equal(np.array(T_mod), np.array(T_mod_ref)), "T_mod incorreto"

print("Exercício correto!")

Exercício correto!


---

## **Exercício 5: Operações com conjuntos**

Considere os seguintes conjuntos de valores:

A = {1, 2, 3, 4, 5}

B = {3, 4, 5, 6, 7}

---

## Tarefas

1. Crie manualmente (usando loops e `in`, sem usar operadores prontos como `&` ou `|`):

   - um conjunto `intersec` contendo os elementos que estão em **A e B**  
   - um conjunto `uniao` contendo todos os elementos de **A ou B**  

2. Crie um conjunto `diff` contendo os elementos que estão em **A mas não em B**.

3. Crie um conjunto `simetrica` contendo os elementos que estão em apenas um dos conjuntos (ou seja, pertencem a A ou B, mas não a ambos).

---

## Restrições

- Não usar operadores prontos:
  - `&`, `|`, `-`, `^`
- Usar apenas:
  - loops (`for`)
  - operador `in`
  - `.add()`

---

## Dicas

- Para interseção:
  - percorra um conjunto e verifique se o elemento está no outro  

- Para união:
  - adicione todos os elementos de ambos  

- Para diferença:
  - verifique se o elemento NÃO está no outro conjunto  

In [8]:
A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}

intersec = set()

for x in A:
  if x in B:
    intersec.add(x)

print(intersec)
uniao = set()

for x in A:
  uniao.add(x)

for x in B:
  if x not in uniao:
    uniao.add(x)

print(uniao)

diff = set()

for x in A:
  if x not in B:
    diff.add(x)

print(diff)

simetrica = set()

# Calculate symmetric difference
for x in uniao:
  if x not in intersec:
    simetrica.add(x)

print(simetrica)

{3, 4, 5}
{1, 2, 3, 4, 5, 6, 7}
{1, 2}
{1, 2, 6, 7}


### **Checagem**:

In [9]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

A_ref = {1, 2, 3, 4, 5}
B_ref = {3, 4, 5, 6, 7}

inter_ref = {3, 4, 5}
uniao_ref = {1, 2, 3, 4, 5, 6, 7}
diff_ref = {1, 2}
simetrica_ref = {1, 2, 6, 7}

assert isinstance(intersec, set), "intersec deve ser um set"
assert isinstance(uniao, set), "uniao deve ser um set"
assert isinstance(diff, set), "diff deve ser um set"
assert isinstance(simetrica, set), "simetrica deve ser um set"

assert intersec == inter_ref, "Interseção incorreta"
assert uniao == uniao_ref, "União incorreta"
assert diff == diff_ref, "Diferença incorreta"
assert simetrica == simetrica_ref, "Diferença simétrica incorreta"

print("Exercício correto!")

Exercício correto!


---
## **Exercício 6: Tuplas e coordenadas**

Considere uma lista de pontos no plano cartesiano, onde cada ponto é representado por uma tupla (x, y):

pontos = [(1, 2), (3, 4), (1, 2), (5, 0), (3, 4)]

---

## Tarefas

1. Crie uma nova lista chamada `unicos` contendo apenas os pontos distintos (sem repetição), mantendo a ordem de primeira aparição.

2. Usando **desempacotamento de tuplas**, calcule a distância de cada ponto até a origem (0, 0), utilizando a fórmula:

distância = √(x² + y²)

Armazene os resultados em uma lista chamada `distancias`.

3. Encontre o ponto mais distante da origem e armazene-o na variável `mais_distante`.

---

## Restrições

- Use tuplas normalmente (não converta para listas)
- Use loops (`for`)
- Use desempacotamento: `for (x, y) in ...`
- Evite funções prontas que resolvam tudo diretamente

---

## Dicas

- Para remover duplicatas mantendo ordem:
  - percorra a lista e verifique se o elemento já apareceu  

- A tupla representa um ponto fixo (imutável)  

- Você pode comparar distâncias para encontrar o ponto mais distante  

In [10]:
# Escreva seu código aqui
import math

pontos = [(1, 2), (3, 4), (1, 2), (5, 0), (3, 4)]

# 1. Lista de pontos únicos (mantendo ordem)
unicos = []

for p in pontos:
    if p not in unicos:
        unicos.append(p)

# 2. Calcular distâncias até a origem
distancias = []

for (x, y) in pontos:  # desempacotamento
    d = math.sqrt(x**2 + y**2)
    distancias.append(d)

# 3. Encontrar o ponto mais distante
maior_dist = -1
mais_distante = None

for (x, y) in pontos:
    d = math.sqrt(x**2 + y**2)

    if d > maior_dist:
        maior_dist = d
        mais_distante = (x, y)

# Resultados
print("Pontos únicos:", unicos)
print("Distâncias:", distancias)
print("Ponto mais distante:", mais_distante)

Pontos únicos: [(1, 2), (3, 4), (5, 0)]
Distâncias: [2.23606797749979, 5.0, 2.23606797749979, 5.0, 5.0]
Ponto mais distante: (3, 4)


### **Checagem**:

In [11]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

import numpy as np

# Referência
pontos_ref = [(1, 2), (3, 4), (1, 2), (5, 0), (3, 4)]

unicos_ref = [(1, 2), (3, 4), (5, 0)]

dist_ref = [
    np.sqrt(1**2 + 2**2),
    np.sqrt(3**2 + 4**2),
    np.sqrt(1**2 + 2**2),
    np.sqrt(5**2 + 0**2),
    np.sqrt(3**2 + 4**2)
]

assert isinstance(unicos, list), "unicos deve ser lista"
assert unicos == unicos_ref, "Lista de pontos únicos incorreta"

assert isinstance(distancias, list), "distancias deve ser lista"
for a, b in zip(distancias, dist_ref):
    assert abs(a - b) < 1e-6, "Distância incorreta"

assert mais_distante in [(3, 4), (5, 0)], "Ponto mais distante incorreto"

print("Exercício correto!")

Exercício correto!


---

## **Exercício 7: Organização de Dados com Dicionários**

Considere o seguinte conjunto de dados, onde cada chave representa o nome de um aluno e o valor associado é uma lista com suas notas:

```
notas = {
          "Hofstadter": [8, 7, 9],
          "Cooper": [10, 10, 10],
          "Wolowitz": [7, 5, 8],
          "Koothrappali": [9, 7, 7]
        }
```




---

## Tarefas

1. Crie um novo dicionário chamado `medias`, onde:
   - cada chave é o nome do aluno  
   - cada valor é a média de suas notas  

2. Encontre o aluno com a maior média e armazene:
   - o nome em `melhor_aluno`  
   - o valor da média em `melhor_media`  

3. Crie uma lista chamada `summa_cum_laude` contendo os nomes dos alunos cuja média é **maior ou igual a 9**.

---

## Restrições

- Use loops (`for`)
- Use acesso por chave (`dict[chave]`)
- Evite funções prontas como `np.mean` ou similares

---

## Dicas

- Para calcular a média:
  - some os valores da lista  
  - divida pela quantidade de elementos  

- Você pode percorrer o dicionário com:
  - `for nome, notas in notas.items()`  

- Compare valores para encontrar o maior  


In [12]:
notas = {
    "Hofstadter": [8, 7, 9],
    "Cooper": [10, 10, 10],
    "Wolowitz": [7, 5, 8],
    "Koothrappali": [9, 7, 7]
}

# 1. Calcular médias
medias = {}

for nome, lista_notas in notas.items():
    soma = 0
    quantidade = 0

    for n in lista_notas:
        soma += n
        quantidade += 1

    media = soma / quantidade
    medias[nome] = media

# 2. Encontrar melhor aluno
melhor_aluno = None
melhor_media = -1

for nome in medias:
    if medias[nome] > melhor_media:
        melhor_media = medias[nome]
        melhor_aluno = nome

# 3. Lista summa cum laude (média >= 9)
summa_cum_laude = []

for nome in medias:
    if medias[nome] >= 9:
        summa_cum_laude.append(nome)

# Resultados
print("Médias:", medias)
print("Melhor aluno:", melhor_aluno)
print("Melhor média:", melhor_media)
print("Summa cum laude:", summa_cum_laude)

Médias: {'Hofstadter': 8.0, 'Cooper': 10.0, 'Wolowitz': 6.666666666666667, 'Koothrappali': 7.666666666666667}
Melhor aluno: Cooper
Melhor média: 10.0
Summa cum laude: ['Cooper']


### **Checagem**:

In [13]:
# Não altere esse código! Apenas rode-o para checar seu resultado...
notas_ref = {
    "Hofstadter": [8, 7, 9],
    "Cooper": [10, 10, 10],
    "Wolowitz": [7, 5, 8],
    "Koothrappali": [9, 7, 7]
}

medias_ref = {
    "Hofstadter": 8.0,
    "Cooper": 10.0,
    "Wolowitz": 20/3,
    "Koothrappali": 23/3
}

melhor_aluno_ref = "Cooper"
melhor_media_ref = 10.0

summa_ref = ["Cooper"]

assert isinstance(medias, dict), "medias deve ser um dicionário"

for nome in medias_ref:
    assert nome in medias, f"{nome} não encontrado em medias"
    assert abs(medias[nome] - medias_ref[nome]) < 1e-6, f"Média incorreta para {nome}"

assert melhor_aluno == melhor_aluno_ref, "Melhor aluno incorreto"
assert abs(melhor_media - melhor_media_ref) < 1e-6, "Melhor média incorreta"

assert isinstance(summa_cum_laude, list), "summa_cum_laude deve ser uma lista"
assert sorted(summa_cum_laude) == sorted(summa_ref), "Lista summa_cum_laude incorreta"

print("Exercício correto!")

Exercício correto!


---
## **Exercício 8: Similaridade entre perfis**

Uma plataforma educacional está analisando o comportamento de seus alunos com base nos tópicos que cada um estudou ao longo do semestre.

Cada aluno é representado por um conjunto (`set`) de tópicos estudados. O sistema deseja identificar quais alunos possuem maior afinidade acadêmica, ou seja, estudaram conteúdos mais semelhantes.

Os dados disponíveis são:

```
perfis = {
          "Hofstadter": {"logica", "algebra", "ia"},
          "Cooper": {"fisica", "calculo", "logica"},
          "Wolowitz": {"engenharia", "fisica"},
          "Koothrappali": {"astronomia", "fisica", "calculo"}
        }
```

---

## Tarefas

1. Para cada par de alunos distintos, calcule a quantidade de tópicos em comum entre eles.

2. Armazene esses valores em um dicionário chamado `similaridade`, onde:
   - a chave é uma tupla com dois nomes de alunos  
   - o valor é o número de tópicos em comum  

   Exemplo de chave:
   ("Hofstadter", "Cooper")

3. Encontre o par de alunos com **maior similaridade** e armazene:
   - o par em `par_mais_similar`  
   - o valor da similaridade em `valor_similaridade`  

---

## Restrições

- Use:
  - loops (`for`)
  - sets (`in`, interseção manual ou lógica equivalente)
  - dicionários
  - tuplas como chave  

- Evite:
  - funções prontas que resolvam diretamente (como métodos automáticos de similaridade)

---

## Dicas

- Para comparar pares:
  - percorra todos os alunos  
  - evite comparar um aluno com ele mesmo  
  - evite repetir pares (A,B) e (B,A)  

- Para contar interseção:
  - percorra um conjunto e verifique se os elementos estão no outro  

- Comece inicializando a melhor similaridade com um valor baixo  

In [14]:
# Entre com seu código aqui
perfis = {
    "Hofstadter": {"logica", "algebra", "ia"},
    "Cooper": {"fisica", "calculo", "logica"},
    "Wolowitz": {"engenharia", "fisica"},
    "Koothrappali": {"astronomia", "fisica", "calculo"}
}

# Lista de nomes (para controlar os pares)
nomes = list(perfis.keys())

# 1. Calcular similaridade entre todos os pares
similaridade = {}

for i in range(len(nomes)):
    for j in range(i + 1, len(nomes)):  # evita repetir pares e auto-comparação
        aluno1 = nomes[i]
        aluno2 = nomes[j]

        set1 = perfis[aluno1]
        set2 = perfis[aluno2]

        # Contar interseção manualmente
        contador = 0
        for topico in set1:
            if topico in set2:
                contador += 1

        similaridade[(aluno1, aluno2)] = contador

# 2. Encontrar o par mais similar
par_mais_similar = None
valor_similaridade = -1

for par in similaridade:
    if similaridade[par] > valor_similaridade:
        valor_similaridade = similaridade[par]
        par_mais_similar = par

# Resultados
print("Similaridade entre pares:")
for par in similaridade:
    print(par, "->", similaridade[par])

print("\nPar mais similar:", par_mais_similar)
print("Valor da similaridade:", valor_similaridade)

Similaridade entre pares:
('Hofstadter', 'Cooper') -> 1
('Hofstadter', 'Wolowitz') -> 0
('Hofstadter', 'Koothrappali') -> 0
('Cooper', 'Wolowitz') -> 1
('Cooper', 'Koothrappali') -> 2
('Wolowitz', 'Koothrappali') -> 1

Par mais similar: ('Cooper', 'Koothrappali')
Valor da similaridade: 2


### **Checagem**:

In [15]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

perfis_ref = {
    "Hofstadter": {"logica", "algebra", "ia"},
    "Cooper": {"fisica", "calculo", "logica"},
    "Wolowitz": {"engenharia", "fisica"},
    "Koothrappali": {"astronomia", "fisica", "calculo"}
}

similaridade_ref = {
    ("Hofstadter", "Cooper"): 1,
    ("Hofstadter", "Wolowitz"): 0,
    ("Hofstadter", "Koothrappali"): 0,
    ("Cooper", "Wolowitz"): 1,
    ("Cooper", "Koothrappali"): 2,
    ("Wolowitz", "Koothrappali"): 1
}

par_ref = ("Cooper", "Koothrappali")
valor_ref = 2

assert isinstance(similaridade, dict), "similaridade deve ser um dicionário"

for par in similaridade_ref:
    assert par in similaridade, f"Par {par} não encontrado"
    assert similaridade[par] == similaridade_ref[par], f"Valor incorreto para {par}"

assert par_mais_similar == par_ref, "Par mais similar incorreto"
assert valor_similaridade == valor_ref, "Valor de similaridade incorreto"

print("Exercício correto!")

Exercício correto!


---

## **Exercício 9: Sistema de monitoramento automático para florestas encantadas utilizando `for`**

# 🏴‍☠️ Exercício 9 — Alianças no Novo Mundo

No Novo Mundo, alianças entre tripulações de piratas são frequentemente formadas com base em interesses em comum e complementaridade de habilidades.

Cada tripulação é representada por um dicionário contendo:

- uma lista de membros (`list`)
- um conjunto de especialidades (`set`)

Os dados disponíveis são:


```
tripulacoes = {
    "Chapéu de Palha": {
        "membros": ["Luffy", "Zoro", "Nami"],
        "especialidades": {"combate", "navegacao", "estrategia"}
    },
    "Coração": {
        "membros": ["Law", "Bepo"],
        "especialidades": {"medicina", "combate"}
    },
    "Kid": {
        "membros": ["Kid", "Killer"],
        "especialidades": {"combate", "engenharia"}
    },
    "Big Mom": {
        "membros": ["Katakuri", "Perospero"],
        "especialidades": {"combate", "estrategia"}
    }
}
```

---

## Tarefas

1. Para cada par de tripulações distintas, calcule um **score de aliança**, definido como:

   score = (número de especialidades em comum) + (número total de membros das duas tripulações)

2. Armazene os resultados em um dicionário `scores`, onde:
   - a chave é uma tupla com os nomes das duas tripulações  
   - o valor é o score calculado  

3. Encontre o par de tripulações com o maior score e armazene:
   - o par em `melhor_par`  
   - o valor em `melhor_score`  

4. Para o melhor par encontrado, crie um conjunto `especialidades_unicas` contendo:
   - todas as especialidades presentes em apenas uma das duas tripulações (ou seja, não compartilhadas)

---

## Restrições

- Use:
  - dicionários
  - listas
  - sets
  - tuplas
  - loops (`for`)

- Evite:
  - operadores prontos como `&`, `|`, `^`
  - funções que resolvam diretamente os cálculos

---

## Dicas

- Para gerar pares:
  - percorra as chaves do dicionário  
  - evite pares repetidos e auto-comparações  

- Para contar especialidades em comum:
  - percorra um set e use `in`  

- Para contar membros:
  - use o tamanho das listas  

- Para especialidades únicas:
  - pense em elementos que estão em um conjunto mas não no outro  

In [16]:
tripulacoes = {
    "Chapéu de Palha": {
        "membros": ["Luffy", "Zoro", "Nami"],
        "especialidades": {"combate", "navegacao", "estrategia"}
    },
    "Coração": {
        "membros": ["Law", "Bepo"],
        "especialidades": {"medicina", "combate"}
    },
    "Kid": {
        "membros": ["Kid", "Killer"],
        "especialidades": {"combate", "engenharia"}
    },
    "Big Mom": {
        "membros": ["Katakuri", "Perospero"],
        "especialidades": {"combate", "estrategia"}
    }
}

# Lista com os nomes das tripulações
nomes = list(tripulacoes.keys())

# 1. Calcular scores de aliança
scores = {}

for i in range(len(nomes)):
    for j in range(i + 1, len(nomes)):  # evita repetição e auto-comparação
        t1 = nomes[i]
        t2 = nomes[j]

        esp1 = tripulacoes[t1]["especialidades"]
        esp2 = tripulacoes[t2]["especialidades"]

        membros1 = tripulacoes[t1]["membros"]
        membros2 = tripulacoes[t2]["membros"]

        # Contar especialidades em comum (manual)
        comuns = 0
        for e in esp1:
            if e in esp2:
                comuns += 1

        # Contar total de membros
        total_membros = len(membros1) + len(membros2)

        score = comuns + total_membros
        scores[(t1, t2)] = score

# 2. Encontrar o melhor par
melhor_par = None
melhor_score = -1

for par in scores:
    if scores[par] > melhor_score:
        melhor_score = scores[par]
        melhor_par = par

# 3. Especialidades únicas do melhor par
esp_a = tripulacoes[melhor_par[0]]["especialidades"]
esp_b = tripulacoes[melhor_par[1]]["especialidades"]

especialidades_unicas = set()

# Elementos em A mas não em B
for e in esp_a:
    if e not in esp_b:
        especialidades_unicas.add(e)

# Elementos em B mas não em A
for e in esp_b:
    if e not in esp_a:
        especialidades_unicas.add(e)

# Resultados
print("Scores de aliança:")
for par in scores:
    print(par, "->", scores[par])

print("\nMelhor par:", melhor_par)
print("Melhor score:", melhor_score)
print("Especialidades únicas do melhor par:", especialidades_unicas)

Scores de aliança:
('Chapéu de Palha', 'Coração') -> 6
('Chapéu de Palha', 'Kid') -> 6
('Chapéu de Palha', 'Big Mom') -> 7
('Coração', 'Kid') -> 5
('Coração', 'Big Mom') -> 5
('Kid', 'Big Mom') -> 5

Melhor par: ('Chapéu de Palha', 'Big Mom')
Melhor score: 7
Especialidades únicas do melhor par: {'navegacao'}


### **Checagem**:

In [17]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

scores_ref = {
    ("Chapéu de Palha", "Coração"): 1 + (3 + 2),
    ("Chapéu de Palha", "Kid"): 1 + (3 + 2),
    ("Chapéu de Palha", "Big Mom"): 2 + (3 + 2),
    ("Coração", "Kid"): 1 + (2 + 2),
    ("Coração", "Big Mom"): 1 + (2 + 2),
    ("Kid", "Big Mom"): 1 + (2 + 2)
}

melhor_par_ref = ("Chapéu de Palha", "Big Mom")
melhor_score_ref = 7

especialidades_unicas_ref = {"navegacao"}

assert isinstance(scores, dict), "scores deve ser um dicionário"

for par in scores_ref:
    assert par in scores, f"Par {par} não encontrado"
    assert scores[par] == scores_ref[par], f"Score incorreto para {par}"

assert melhor_par == melhor_par_ref, "Melhor par incorreto"
assert melhor_score == melhor_score_ref, "Melhor score incorreto"

assert isinstance(especialidades_unicas, set), "Deve ser um set"
assert especialidades_unicas == especialidades_unicas_ref, "Especialidades únicas incorretas"

print("Exercício correto!")

Exercício correto!


---

## **Exercício 10: Liga Pokémon**


A Liga Pokémon está conduzindo um estudo para entender quais treinadores possuem estilos de batalha mais compatíveis — seja para formar duplas estratégicas ou prever confrontos equilibrados.

Cada treinador possui uma equipe composta por Pokémon com características distintas. Para este estudo, cada Pokémon é representado por uma tupla contendo:

- nome (string)
- tipo principal (string)
- uma lista de atributos numéricos no formato:
  [ataque, defesa, velocidade]

Os dados disponíveis são:

```
treinadores = {
    "Ash": [
        ("Pikachu", "eletrico", [90, 60, 110]),
        ("Charizard", "fogo", [100, 80, 90])
    ],
    "Misty": [
        ("Starmie", "agua", [85, 75, 100]),
        ("Gyarados", "agua", [110, 79, 81])
    ],
    "Brock": [
        ("Onix", "pedra", [45, 160, 70]),
        ("Geodude", "pedra", [80, 100, 20])
    ],
    "Gary": [
        ("Blastoise", "agua", [103, 120, 78]),
        ("Arcanine", "fogo", [110, 80, 95])
    ],
    "Erika": [
        ("Vileplume", "planta", [80, 85, 50]),
        ("Tangela", "planta", [55, 115, 60])
    ],
    "Lt. Surge": [
        ("Raichu", "eletrico", [90, 55, 110]),
        ("Electrode", "eletrico", [50, 70, 150])
    ],
    "Koga": [
        ("Crobat", "veneno", [90, 80, 130]),
        ("Muk", "veneno", [105, 75, 50])
    ],
    "Sabrina": [
        ("Alakazam", "psiquico", [50, 45, 120]),
        ("MrMime", "psiquico", [45, 65, 90])
    ],
    "Blaine": [
        ("Magmar", "fogo", [95, 57, 93]),
        ("Rapidash", "fogo", [100, 70, 105])
    ],
    "Giovanni": [
        ("Nidoking", "terra", [102, 77, 85]),
        ("Rhydon", "terra", [130, 120, 40])
    ],
    "Lorelei": [
        ("Lapras", "agua", [85, 80, 60]),
        ("Cloyster", "agua", [95, 180, 70])
    ],
    "Bruno": [
        ("Machamp", "lutador", [130, 80, 55]),
        ("Hitmonlee", "lutador", [120, 53, 87])
    ],
    "Agatha": [
        ("Gengar", "fantasma", [65, 60, 110]),
        ("Haunter", "fantasma", [50, 45, 95])
    ],
    "Lance": [
        ("Dragonite", "dragao", [134, 95, 80]),
        ("Gyarados", "agua", [110, 79, 81])
    ]
}
```

---

Ao longo da análise, os pesquisadores perceberam que não basta considerar apenas a força bruta. Dois treinadores podem ser considerados "compatíveis" se:

- possuem estilos semelhantes (tipos de Pokémon parecidos)
- possuem níveis de poder próximos
- ou se complementam bem em termos de atributos

A partir disso, você deverá implementar um pipeline completo de análise.

---

## Tarefas

### 1. Cálculo de poder individual
Para cada Pokémon:
- calcule o poder individual (soma dos atributos)

---

### 2. Poder médio por treinador
Calcule a média dos poderes individuais de cada treinador  
→ armazene em `poder_medio`

---

### 3. Tipos e diversidade
Para cada treinador:
- crie um set de tipos → `tipos`
- calcule a diversidade (quantidade de tipos) → `diversidade`

---

### 4. Similaridade entre treinadores
Para cada par de treinadores:

score = (tipos em comum)
        + (diversidade total)
        - |diferença de poder médio|

→ armazene em `similaridade`

Importante:
- evite pares repetidos
- calcule valor absoluto manualmente

---

### 5. Melhor par
Escolha o par com maior score

Desempate:
- maior soma dos poderes médios

→ `melhor_par`, `melhor_score`

---

### 6. Matriz do confronto
Crie `M` com todos os Pokémon do melhor par  
(linhas = Pokémon, colunas = atributos)

---

### 7. Análise da matriz
Sem usar funções prontas:

- soma por linha → encontrar Pokémon dominante  
- soma por coluna → `soma_colunas`

---

## Restrição

- Evite funções prontas (`np.sum`, etc.)  

In [23]:
treinadores = {
    "Ash": [
        ("Pikachu", "eletrico", [90, 60, 110]),
        ("Charizard", "fogo", [100, 80, 90])
    ],
    "Misty": [
        ("Starmie", "agua", [85, 75, 100]),
        ("Gyarados", "agua", [110, 79, 81])
    ],
    "Brock": [
        ("Onix", "pedra", [45, 160, 70]),
        ("Geodude", "pedra", [80, 100, 20])
    ],
    "Gary": [
        ("Blastoise", "agua", [103, 120, 78]),
        ("Arcanine", "fogo", [110, 80, 95])
    ],
    "Erika": [
        ("Vileplume", "planta", [80, 85, 50]),
        ("Tangela", "planta", [55, 115, 60])
    ],
    "Lt. Surge": [
        ("Raichu", "eletrico", [90, 55, 110]),
        ("Electrode", "eletrico", [50, 70, 150])
    ],
    "Koga": [
        ("Crobat", "veneno", [90, 80, 130]),
        ("Muk", "veneno", [105, 75, 50])
    ],
    "Sabrina": [
        ("Alakazam", "psiquico", [50, 45, 120]),
        ("MrMime", "psiquico", [45, 65, 90])
    ],
    "Blaine": [
        ("Magmar", "fogo", [95, 57, 93]),
        ("Rapidash", "fogo", [100, 70, 105])
    ],
    "Giovanni": [
        ("Nidoking", "terra", [102, 77, 85]),
        ("Rhydon", "terra", [130, 120, 40])
    ],
    "Lorelei": [
        ("Lapras", "agua", [85, 80, 60]),
        ("Cloyster", "agua", [95, 180, 70])
    ],
    "Bruno": [
        ("Machamp", "lutador", [130, 80, 55]),
        ("Hitmonlee", "lutador", [120, 53, 87])
    ],
    "Agatha": [
        ("Gengar", "fantasma", [65, 60, 110]),
        ("Haunter", "fantasma", [50, 45, 95])
    ],
    "Lance": [
        ("Dragonite", "dragao", [134, 95, 80]),
        ("Gyarados", "agua", [110, 79, 81])
    ]
}

# 1 e 2. Poder individual + média
poder_medio = {}

for nome in treinadores:
    soma_total = 0
    qtd = 0

    for (poke, tipo, atributos) in treinadores[nome]:
        soma = 0
        for v in atributos:
            soma += v

        soma_total += soma
        qtd += 1

    media = soma_total / qtd
    poder_medio[nome] = media

# 3. Tipos e diversidade
tipos = {}
diversidade = {}

for nome in treinadores:
    conj = set()

    for (poke, tipo, atributos) in treinadores[nome]:
        if tipo not in conj:
            conj.add(tipo)

    tipos[nome] = conj
    diversidade[nome] = len(conj)

# 4. Similaridade
nomes = list(treinadores.keys())
similaridade = {}

for i in range(len(nomes)):
    for j in range(i + 1, len(nomes)):
        t1 = nomes[i]
        t2 = nomes[j]

        # tipos em comum
        comuns = 0
        for tp in tipos[t1]:
            if tp in tipos[t2]:
                comuns += 1

        # diversidade total
        div_total = diversidade[t1] + diversidade[t2]

        # diferença absoluta manual
        diff = poder_medio[t1] - poder_medio[t2]
        if diff < 0:
            diff = -diff

        score = comuns + div_total - diff
        similaridade[(t1, t2)] = score

# 5. Melhor par
melhor_par = None
melhor_score = -9999

for par in similaridade:
    score = similaridade[par]

    if melhor_par is None:
        melhor_par = par
        melhor_score = score
    else:
        if score > melhor_score:
            melhor_par = par
            melhor_score = score
        elif score == melhor_score:
            soma_medias_atual = poder_medio[par[0]] + poder_medio[par[1]]
            soma_medias_melhor = poder_medio[melhor_par[0]] + poder_medio[melhor_par[1]]

            if soma_medias_atual > soma_medias_melhor:
                melhor_par = par
                melhor_score = score

# 6. Matriz M
M = []
nomes_pokemons = []

for treinador in melhor_par:
    for (poke, tipo, atributos) in treinadores[treinador]:
        M.append(atributos)
        nomes_pokemons.append(poke)

M = np.array(M) # Convert M to a NumPy array

# 7. Análise da matriz

# Soma por linha (pokémon dominante)
maior = -1
dominante = None
idx_dominante = -1 # Initialize idx_dominante

for i in range(len(M)):
    soma = 0
    for v in M[i]:
        soma += v

    if soma > maior:
        maior = soma
        dominante = nomes_pokemons[i]
        idx_dominante = i # Store the index

# Soma por coluna
soma_colunas = []

for j in range(3):  # 3 atributos
    soma = 0
    for i in range(len(M)):
        soma += M[i][j]
    soma_colunas.append(soma)

# Resultados
print("Poder médio:", poder_medio)
print("\nMelhor par:", melhor_par)
print("Score:", melhor_score)
print("\nMatriz M:", M)
print("Pokémon dominante:", dominante)
print("Soma das colunas:", soma_colunas)


Poder médio: {'Ash': 265.0, 'Misty': 265.0, 'Brock': 237.5, 'Gary': 293.0, 'Erika': 222.5, 'Lt. Surge': 262.5, 'Koga': 265.0, 'Sabrina': 207.5, 'Blaine': 260.0, 'Giovanni': 277.0, 'Lorelei': 285.0, 'Bruno': 262.5, 'Agatha': 212.5, 'Lance': 289.5}

Melhor par: ('Ash', 'Misty')
Score: 3.0

Matriz M: [[ 90  60 110]
 [100  80  90]
 [ 85  75 100]
 [110  79  81]]
Pokémon dominante: Charizard
Soma das colunas: [np.int64(385), np.int64(294), np.int64(381)]


### **Checagem**:

In [24]:
# Não altere esse código! Apenas rode-o para checar seu resultado...

import numpy as np

assert isinstance(poder_medio, dict)
assert isinstance(tipos, dict)
assert isinstance(diversidade, dict)
assert isinstance(similaridade, dict)

for k in tipos:
    assert diversidade[k] == len(tipos[k]), f"Diversidade inconsistente em {k}"

for (a, b), v in similaridade.items():
    assert a != b, "Par inválido (mesmo treinador)"
    assert (b, a) not in similaridade, "Par duplicado"

assert melhor_par in similaridade, "Melhor par não encontrado"

assert isinstance(M, np.ndarray)
assert M.shape[1] == 3, "Cada Pokémon deve ter 3 atributos"

assert len(soma_colunas) == 3, "Deve ter 3 colunas"

assert 0 <= idx_dominante < M.shape[0], "Índice inválido"

print("Exercício correto!")

Exercício correto!


---

<center>
<img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/Logo_Unesp.svg" width="400" style="float: left; margin-right: 5px;" border="0px" />
</center>